const GET_RECORDS = 'GET_RECORDS';
const CHANGE_PLAYER = 'CHANGE_PLAYER';
const CURRENT_PLAYER_ONE = 'CURRENT_PLAYER_ONE';
const CURRENT_PLAYER_TWO = 'CURRENT_PLAYER_TWO';



module.exports = {
    GET_RECORDS,
    CHANGE_PLAYER,
    CURRENT_PLAYER_ONE,
    CURRENT_PLAYER_TWO
}